version: '3'
services:
  stream-front-end:
    build:
      context: ./stream-front-end
    ports:
      - "3000:3000"

  stream-backend:
    build:
      context: ./stream-backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video_stream
